import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, FileText, Save, ShieldCheck } from "lucide-react";
import { BookingStatus } from "@prisma/client";

import { toggleCallOutcomeVisibilityAction, upsertCallOutcomeAction } from "@/server/actions/call-outcome.actions";
import { requireRole } from "@/lib/auth/get-current-user";
import { prisma } from "@/lib/prisma";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

export default async function ExpertBookingOutcomePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams?: Promise<{ saved?: string; error?: string }> }) {
  const { user } = await requireRole(["expert", "admin"]);
  const { id } = await params;
  const resolvedSearchParams = searchParams ? await searchParams : {};

  const booking = await prisma.booking.findUnique({
    where: { id },
    include: { buyer: true, expert: { include: { user: true } }, service: true, outcome: true },
  });
  if (!booking) notFound();
  if (booking.expert.userId !== user.id && user.role !== "ADMIN") redirect("/expert/bookings");

  const canEdit = booking.status === BookingStatus.COMPLETED;

  return <main><section className="relative overflow-hidden border-b border-[var(--border)]"><div className="surface-grid absolute inset-0 opacity-40" /><div className="container-page relative py-8 md:py-10 lg:py-12"><Link href="/expert/bookings" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--primary-dark)]"><ArrowLeft size={16} />Back to bookings</Link>{resolvedSearchParams.saved ? <div className="mt-6 rounded-2xl border border-[var(--success)]/20 bg-[var(--success-soft)] p-4 text-sm font-bold text-[var(--success)]">Action plan saved.</div> : null}{resolvedSearchParams.error ? <div className="mt-6 rounded-2xl border border-[var(--danger)]/20 bg-[var(--danger-soft)] p-4 text-sm font-bold text-[var(--danger)]">{formatOutcomeError(resolvedSearchParams.error)}</div> : null}<Badge variant="primary" className="mt-8"><FileText size={14} />Action plan</Badge><h1 className="heading-lg mt-5 max-w-4xl text-balance">{booking.outcome ? "Edit buyer action plan." : "Create buyer action plan."}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[var(--muted-foreground)]">For: {booking.service?.title ?? "Booked call"} · Buyer: {booking.buyer.name ?? booking.buyer.email}</p></div></section><section className="container-page py-8 md:py-10 lg:py-12"><div className="grid gap-6 xl:grid-cols-[1fr_360px] xl:items-start"><Card className="p-5 md:p-6">{canEdit ? <OutcomeForm bookingId={booking.id} outcome={booking.outcome} /> : <div><Badge variant="accent">Not ready</Badge><h2 className="mt-4 text-2xl font-black">This booking is not completed yet.</h2><p className="mt-3 text-sm font-medium leading-6 text-[var(--muted-foreground)]">You can create an action plan only after the call is completed.</p></div>}</Card><div className="grid gap-6"><Card soft className="p-5 md:p-6"><Badge variant="success"><ShieldCheck size={14} />Outcome quality</Badge><div className="mt-5 grid gap-3"><Tip text="Summarize the buyer’s problem in simple words." /><Tip text="Write concrete next steps, not vague advice." /><Tip text="Keep safety boundaries clear for sensitive topics." /><Tip text="Add useful links only when they are relevant." /></div></Card>{booking.outcome ? <Card className="p-5 md:p-6"><Badge variant={booking.outcome.isVisibleToBuyer ? "success" : "accent"}>{booking.outcome.isVisibleToBuyer ? <Eye size={14} /> : <EyeOff size={14} />}{booking.outcome.isVisibleToBuyer ? "Visible to buyer" : "Hidden from buyer"}</Badge><form action={toggleCallOutcomeVisibilityAction} className="mt-5"><input type="hidden" name="bookingId" value={booking.id} /><button type="submit" className="btn btn-secondary w-full">{booking.outcome.isVisibleToBuyer ? "Hide from buyer" : "Show to buyer"}</button></form></Card> : null}</div></div></section></main>;
}
function OutcomeForm({ bookingId, outcome }: { bookingId: string; outcome: { problemSummary: string; discussionNotes: string | null; nextSteps: string; usefulLinks: string[]; followUpRecommended: boolean; followUpNote: string | null; isVisibleToBuyer: boolean } | null }) { return <form action={upsertCallOutcomeAction} className="grid gap-5"><input type="hidden" name="bookingId" value={bookingId} /><Field label="Problem summary" htmlFor="problemSummary"><textarea id="problemSummary" name="problemSummary" required minLength={8} rows={4} defaultValue={outcome?.problemSummary ?? ""} className="textarea" placeholder="What problem did the buyer bring to the call?" /></Field><Field label="Discussion notes" htmlFor="discussionNotes"><textarea id="discussionNotes" name="discussionNotes" rows={5} defaultValue={outcome?.discussionNotes ?? ""} className="textarea" placeholder="What was discussed? Optional internal/context notes." /></Field><Field label="Next steps for buyer" htmlFor="nextSteps"><textarea id="nextSteps" name="nextSteps" required minLength={12} rows={7} defaultValue={outcome?.nextSteps ?? ""} className="textarea" placeholder="1. Do this...\n2. Prepare that...\n3. Follow up with..." /></Field><Field label="Useful links" htmlFor="usefulLinks" hint="Optional. One link per line or separated by commas."><textarea id="usefulLinks" name="usefulLinks" rows={3} defaultValue={outcome?.usefulLinks?.join("\n") ?? ""} className="textarea" placeholder="https://example.com" /></Field><div className="grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--card-soft)] p-4"><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="followUpRecommended" defaultChecked={outcome?.followUpRecommended ?? false} /> Follow-up recommended</label><textarea name="followUpNote" rows={3} defaultValue={outcome?.followUpNote ?? ""} className="textarea" placeholder="Optional follow-up note" /><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="isVisibleToBuyer" defaultChecked={outcome?.isVisibleToBuyer ?? true} /> Visible to buyer</label></div><button type="submit" className="btn btn-primary"><Save size={18} />Save action plan</button></form>; }
function Field({ label, htmlFor, hint, children }: { label: string; htmlFor: string; hint?: string; children: React.ReactNode }) { return <div><label htmlFor={htmlFor} className="text-sm font-bold text-[var(--foreground)]">{label}</label>{hint ? <p className="mt-1 text-xs font-medium text-[var(--muted-foreground)]">{hint}</p> : null}<div className="mt-2">{children}</div></div>; }
function Tip({ text }: { text: string }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--card-soft)] p-3 text-sm font-bold leading-6 text-[var(--muted-foreground)]">{text}</div>; }
function formatOutcomeError(error: string) { if (error === "missing-required-fields") return "Please fill problem summary and next steps."; if (error === "booking-not-completed") return "The call must be completed before creating an action plan."; return "Something went wrong. Please try again."; }

